version: '3.4'

services:
  test-db:
    container_name: xapo-test-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'test'
    ports:
      - 3307:3306

  test:
    container_name: xapo-test-app
    build: .
    depends_on:
      - test-db
    env_file:
      - .env
      - .secret
    environment:
      MYSQL_HOST: 'test-db'
      MYSQL_DATABASE: 'test'
      ENVIRONMENT: 'test'
      FLASK_ENV: 'development'
      FLASK_DEBUG: 'True'
      FLASK_APP: main.py
    command: flask run --host=0.0.0.0
    ports:
      - 5001:5000
    volumes:
      - .:/app
