version: '3.4'

services:
  db:
    container_name: xapo-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./shared/mysql:/var/lib/mysql

  app:
    container_name: xapo-app
    build: .
    depends_on:
      - db
    env_file:
      - .env
      - .secret
    environment:
      FLASK_ENV: 'development'
      FLASK_DEBUG: 'True'
      FLASK_APP: main.py
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - .:/app
