"""Initial migration.

Revision ID: 89c1e143de42
Revises: 
Create Date: 2020-11-15 02:10:27.391819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c1e143de42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency_rate', sa.Numeric(precision=8), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=8), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker')
    # ### end Alembic commands ###
